# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddMenu(object):
    def setupUi(self, AddMenu):
        if AddMenu.objectName():
                AddMenu.setObjectName("AddMenu")
        AddMenu.resize(850, 517)
        AddMenu.setMinimumSize(QtCore.QSize(600, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        AddMenu.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/titleicon.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddMenu.setWindowIcon(icon)
        AddMenu.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(AddMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.label_item = QtWidgets.QLabel(self.centralwidget)
        self.label_item.setGeometry(QtCore.QRect(60, 210, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_item.setFont(font)
        self.label_item.setStyleSheet("QLabel{\n"
"background-color: rgb(55, 55, 55);\n"
"color: rgb(255, 255, 255);\n"
"border style: None;\n"
"border-radius: 20px;\n"
"}\n"
"")
        self.label_item.setObjectName("label_item")
        self.label_category = QtWidgets.QLabel(self.centralwidget)
        self.label_category.setGeometry(QtCore.QRect(60, 100, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_category.setFont(font)
        self.label_category.setStyleSheet("QLabel{\n"
"background-color: rgb(55, 55, 55);\n"
"color: rgb(255, 255, 255);\n"
"border style: None;\n"
"border-radius: 20px;\n"
"}\n"
"")
        self.label_category.setObjectName("label_category")
        self.comboBox_category = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_category.setGeometry(QtCore.QRect(60, 150, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.comboBox_category.setFont(font)
        self.comboBox_category.setStyleSheet("QComboBox{\n"
"border-style: None;\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox::drop-down{\n"
"border-style: None;\n"
"border-radius: 15px\n"
"}")
        self.comboBox_category.setObjectName("comboBox_category")
        self.comboBox_category.addItem("")
        self.comboBox_category.setItemText(0, "Select Any")
        self.comboBox_category.addItem("")
        self.comboBox_category.addItem("")
        self.comboBox_category.addItem("")
        self.comboBox_category.addItem("")
        self.comboBox_category.addItem("")
        self.lineEdit_additem = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_additem.setGeometry(QtCore.QRect(60, 260, 661, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_additem.setFont(font)
        self.lineEdit_additem.setStyleSheet("QLineEdit{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: None;\n"
"border-radius: 15px;\n"
"}")
        self.lineEdit_additem.setText("")
        self.lineEdit_additem.setObjectName("lineEdit_additem")
        self.pushButton_additem = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_additem.setGeometry(QtCore.QRect(330, 360, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_additem.setFont(font)
        self.pushButton_additem.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 159, 51);\n"
"border style: None;\n"
"border-radius: 20px;\n"
"}")
        self.pushButton_additem.setObjectName("pushButton_additem")
        self.frame_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_menu.setGeometry(QtCore.QRect(20, 60, 800, 400))
        self.frame_menu.setStyleSheet("QFrame\n"
"{\n"
"background-color: rgb(55, 55, 55);\n"
"border-radius: 40px;\n"
"\n"
"}")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.lineEdit_price = QtWidgets.QLineEdit(self.frame_menu)
        self.lineEdit_price.setGeometry(QtCore.QRect(290, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_price.setFont(font)
        self.lineEdit_price.setStyleSheet("QLineEdit{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: None;\n"
"border-radius: 15px;\n"
"}\n"
"")
        self.lineEdit_price.setValidator(QtGui.QDoubleValidator())
        self.lineEdit_price.setText("")
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.label_menuitems = QtWidgets.QLabel(self.centralwidget)
        self.label_menuitems.setGeometry(QtCore.QRect(20, 10, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_menuitems.setFont(font)
        self.label_menuitems.setObjectName("label_menuitems")
        self.label_category_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_category_2.setGeometry(QtCore.QRect(320, 100, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_category_2.setFont(font)
        self.label_category_2.setStyleSheet("QLabel{\n"
"background-color: rgb(55, 55, 55);\n"
"color: rgb(255, 255, 255);\n"
"border style: None;\n"
"border-radius: 20px;\n"
"}\n"
"")
        self.label_category_2.setObjectName("label_category_2")
        self.label_category_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_category_3.setGeometry(QtCore.QRect(480, 100, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_category_3.setFont(font)
        self.label_category_3.setStyleSheet("QLabel{\n"
"background-color: rgb(55, 55, 55);\n"
"color: rgb(255, 255, 255);\n"
"border style: None;\n"
"border-radius: 20px;\n"
"}\n"
"")
        self.label_category_3.setObjectName("label_category_3")
        self.comboBox_category_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_category_2.setGeometry(QtCore.QRect(480, 150, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.comboBox_category_2.setFont(font)
        self.comboBox_category_2.setStyleSheet("QComboBox{\n"
"border-style: None;\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox::drop-down{\n"
"border-style: None;\n"
"border-radius: 15px\n"
"}")
        self.comboBox_category_2.setObjectName("comboBox_category_2")
        self.comboBox_category_2.addItem("")
        self.comboBox_category_2.setItemText(0, "None")
        self.comboBox_category_2.addItem("")
        self.comboBox_category_2.addItem("")
        self.comboBox_category_2.addItem("")
        self.comboBox_category_2.addItem("")
        self.comboBox_category_2.addItem("")
        self.frame_menu.raise_()
        self.comboBox_category.raise_()
        self.lineEdit_additem.raise_()
        self.pushButton_additem.raise_()
        self.label_category.raise_()
        self.label_item.raise_()
        self.label_menuitems.raise_()
        self.label_category_2.raise_()
        self.label_category_3.raise_()
        self.comboBox_category_2.raise_()
        AddMenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddMenu)
        QtCore.QMetaObject.connectSlotsByName(AddMenu)

    def retranslateUi(self, AddMenu):
        _translate = QtCore.QCoreApplication.translate
        AddMenu.setWindowTitle(_translate("AddMenu", "Add Items"))
        self.label_item.setText(_translate("AddMenu", "Item Name"))
        self.label_category.setText(_translate("AddMenu", "Category"))
        self.comboBox_category.setItemText(1, _translate("AddMenu", "Pizza Mania"))
        self.comboBox_category.setItemText(2, _translate("AddMenu", "Pizza"))
        self.comboBox_category.setItemText(3, _translate("AddMenu", "Delicious Sides"))
        self.comboBox_category.setItemText(4, _translate("AddMenu", "Beverages"))
        self.comboBox_category.setItemText(5, _translate("AddMenu", "Desserts"))
        self.pushButton_additem.setText(_translate("AddMenu", "Add Item"))
        self.pushButton_additem.setShortcut(_translate("AddMenu", "Return"))
        self.label_menuitems.setText(_translate("AddMenu", "Add Menu Items"))
        self.label_category_2.setText(_translate("AddMenu", "Price"))
        self.label_category_3.setText(_translate("AddMenu", "Sub Category"))
        self.comboBox_category_2.setItemText(1, _translate("AddMenu", "Simply Veg"))
        self.comboBox_category_2.setItemText(2, _translate("AddMenu", "Veg Treat"))
        self.comboBox_category_2.setItemText(3, _translate("AddMenu", "Paneer Special"))
        self.comboBox_category_2.setItemText(4, _translate("AddMenu", "Veg Feast"))
        self.comboBox_category_2.setItemText(5, _translate("AddMenu", "Veg Special"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow_addmenu = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow_addmenu()
#     ui.setupUi(MainWindow_addmenu)
#     MainWindow_addmenu.show()
#     sys.exit(app.exec_())
