# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminpannel.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminPannel(object):
    def setupUi(self, AdminPannel):
        AdminPannel.setObjectName("AdminPannel")
        AdminPannel.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(AdminPannel)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_addemp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addemp.setGeometry(QtCore.QRect(10, 30, 231, 51))
        self.pushButton_addemp.setObjectName("pushButton_addemp")

        self.pushButton_additems = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_additems.setGeometry(QtCore.QRect(280, 30, 231, 51))
        self.pushButton_additems.setObjectName("pushButton_additems")
        AdminPannel.setCentralWidget(self.centralwidget)

        
        

        self.retranslateUi(AdminPannel)
        QtCore.QMetaObject.connectSlotsByName(AdminPannel)

    def retranslateUi(self, AdminPannel):
        _translate = QtCore.QCoreApplication.translate
        AdminPannel.setWindowTitle(_translate("AdminPannel", "Pizza House"))
        AdminPannel.setWindowIcon(QtGui.QIcon("img/titleicon.jpeg"))
        self.pushButton_addemp.setText(_translate("AdminPannel", "Add Employee"))
        self.pushButton_additems.setText(_translate("AdminPannel", "Add Items"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
