# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createemp.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEmp(object):
    def setupUi(self, AddEmp):
        if AddEmp.objectName():
                AddEmp.setObjectName("AddEmp")
        AddEmp.resize(1280, 720)
        AddEmp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(AddEmp)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 60, 1231, 641))
        self.frame.setStyleSheet("QFrame{\n"
"\n"
"background-color: rgb(55, 55, 55);\n"
"border-radius: 40px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 46, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.lineEdit_fempname = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_fempname.setGeometry(QtCore.QRect(60, 90, 381, 41))
        self.lineEdit_fempname.setFont(QtGui.QFont("Segoe UI",14))
        self.lineEdit_fempname.setStyleSheet("QLineEdit{\n"
"border-radius: 20px;\n"
"\n"
"}")
        self.lineEdit_fempname.setObjectName("lineEdit_fempname")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(60, 176, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.lineEdit_fcontact = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_fcontact.setGeometry(QtCore.QRect(60, 220, 381, 41))
        self.lineEdit_fcontact.setFont(QtGui.QFont("Segoe UI",14))
        self.lineEdit_fcontact.setStyleSheet("QLineEdit{\n"
"border-radius: 20px;\n"
"\n"
"}")
        self.lineEdit_fcontact.setValidator(QtGui.QRegExpValidator(QtCore.QRegExp("[0-9]{10}")))
        self.lineEdit_fcontact.setObjectName("lineEdit_fcontact")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(60, 296, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.lineEdit_faadhar = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_faadhar.setGeometry(QtCore.QRect(60, 340, 381, 41))
        self.lineEdit_faadhar.setFont(QtGui.QFont("Segoe UI",14))
        self.lineEdit_faadhar.setStyleSheet("QLineEdit{\n"
"border-radius: 20px;\n"
"\n"
"}")
        self.lineEdit_faadhar.setValidator(QtGui.QRegExpValidator(QtCore.QRegExp("[0-9]{12}")))
        self.lineEdit_faadhar.setObjectName("lineEdit_faadhar")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(60, 416, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.lineEdit_fpost = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_fpost.setGeometry(QtCore.QRect(60, 460, 381, 41))
        self.lineEdit_fpost.setFont(QtGui.QFont("Segoe UI",14))
        self.lineEdit_fpost.setStyleSheet("QLineEdit{\n"
"border-radius: 20px;\n"
"\n"
"}")
        self.lineEdit_fpost.setObjectName("lineEdit_fpost")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(780, 176, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.lineEdit_fempid = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_fempid.setGeometry(QtCore.QRect(780, 220, 381, 41))
        self.lineEdit_fempid.setFont(QtGui.QFont("Segoe UI",14))
        self.lineEdit_fempid.setStyleSheet("QLineEdit{\n"
"border-radius: 20px;\n"
"\n"
"}")
        self.lineEdit_fempid.setObjectName("lineEdit_fempid")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(780, 296, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.lineEdit_femppass = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_femppass.setGeometry(QtCore.QRect(780, 340, 381, 41))
        self.lineEdit_femppass.setFont(QtGui.QFont("Segoe UI",14))
        self.lineEdit_femppass.setStyleSheet("QLineEdit{\n"
"border-radius: 20px;\n"
"\n"
"}")
        self.lineEdit_femppass.setObjectName("lineEdit_femppass")
        self.pushButton_createpro = QtWidgets.QPushButton(self.frame)
        self.pushButton_createpro.setGeometry(QtCore.QRect(780, 460, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.pushButton_createpro.setFont(font)
        self.pushButton_createpro.setStyleSheet("QPushButton{\n"
"border-style: None;\n"
"border-radius: 20px;\n"
"    background-color: rgb(255, 159, 51);\n"
"}")
        self.pushButton_createpro.setObjectName("pushButton_createpro")
        self.label_empimg = QtWidgets.QLabel(self.frame)
        self.label_empimg.setGeometry(QtCore.QRect(780, 80, 121, 81))
        self.label_empimg.setStyleSheet("QLabel{\n"
"border-style: None;\n"
"border-radius: 20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.label_empimg.setText("")
        self.label_empimg.setObjectName("label_empimg")
        self.pushButton_upimg = QtWidgets.QPushButton(self.frame)
        self.pushButton_upimg.setGeometry(QtCore.QRect(930, 130, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButton_upimg.setFont(font)
        self.pushButton_upimg.setStyleSheet("QPushButton{\n"
"border-style: None;\n"
"border-radius: 15px;\n"
"    background-color: rgb(255, 159, 51);\n"
"}")
        self.pushButton_upimg.setObjectName("pushButton_upimg")
        AddEmp.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddEmp)
        QtCore.QMetaObject.connectSlotsByName(AddEmp)

    def retranslateUi(self, AddEmp):
        _translate = QtCore.QCoreApplication.translate
        AddEmp.setWindowTitle(_translate("AddEmp", "Pizza House"))
        AddEmp.setWindowIcon(QtGui.QIcon("img/titleicon.jpeg"))
        self.label.setText(_translate("AddEmp", "Fill Employee Details"))
        self.label_2.setText(_translate("AddEmp", "Name"))
        self.label_3.setText(_translate("AddEmp", "Contact No."))
        self.label_4.setText(_translate("AddEmp", "Aadhaar No."))
        self.label_5.setText(_translate("AddEmp", "Post"))
        self.label_6.setText(_translate("AddEmp", "Employee Id"))
        self.label_7.setText(_translate("AddEmp", "Password"))
        self.pushButton_createpro.setText(_translate("AddEmp", "Create Profile"))
        self.pushButton_upimg.setText(_translate("AddEmp", "Upload Image"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
