# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emp_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EmpLoginWindow(object):
    def setupUi(self, EmpLoginWindow):
        if EmpLoginWindow.objectName():
            EmpLoginWindow.setObjectName("EmpLoginWindow")
        EmpLoginWindow.resize(1280, 720)
        EmpLoginWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(EmpLoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 640, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/pannel.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(880, 10, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(657, 70, 601, 3))
        self.line.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(720, 240, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 102, 0);")
        self.label_3.setObjectName("label_3")
        self.lineEdit_euserid = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_euserid.setGeometry(QtCore.QRect(720, 280, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_euserid.setFont(font)
        self.lineEdit_euserid.setObjectName("lineEdit_euserid")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(720, 340, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 102, 0);")
        self.label_4.setObjectName("label_4")
        self.lineEdit_epass = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_epass.setGeometry(QtCore.QRect(720, 380, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_epass.setFont(font)
        self.lineEdit_epass.setInputMask("")
        self.lineEdit_epass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_epass.setObjectName("lineEdit_epass")
        self.pushButton_eback = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_eback.setGeometry(QtCore.QRect(720, 530, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.pushButton_eback.setFont(font)
        self.pushButton_eback.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 159, 51);\n"
"border-style: None;\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"")
        self.pushButton_eback.setObjectName("pushButton_eback")
        self.pushButton_elogin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_elogin.setGeometry(QtCore.QRect(1070, 530, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.pushButton_elogin.setFont(font)
        self.pushButton_elogin.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 159, 51);\n"
"border-style: None;\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"")
        self.pushButton_elogin.setObjectName("pushButton_elogin")
        EmpLoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(EmpLoginWindow)
        QtCore.QMetaObject.connectSlotsByName(EmpLoginWindow)

    def retranslateUi(self, EmpLoginWindow):
        _translate = QtCore.QCoreApplication.translate
        EmpLoginWindow.setWindowTitle(_translate("EmpLoginWindow", "Pizza House"))
        EmpLoginWindow.setWindowIcon(QtGui.QIcon("img/titleicon.jpeg"))
        self.label_2.setText(_translate("EmpLoginWindow", "Employee"))
        self.label_3.setText(_translate("EmpLoginWindow", "User Id"))
        self.label_4.setText(_translate("EmpLoginWindow", "Password"))
        self.pushButton_eback.setText(_translate("EmpLoginWindow", "Back"))
        self.pushButton_elogin.setText(_translate("EmpLoginWindow", "Login"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     EmpLoginWindow = QtWidgets.QEmpLoginWindow()
#     ui = Ui_EmpLoginWindow()
#     ui.setupUi(EmpLoginWindow)
#     EmpLoginWindow.show()
#     sys.exit(app.exec_())
