# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        if LoginWindow.objectName():
                LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(1280, 720)
        LoginWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 640, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/pannel.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(910, 10, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(657, 70, 601, 3))
        self.line.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_admin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_admin.setGeometry(QtCore.QRect(800, 240, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.pushButton_admin.setFont(font)
        self.pushButton_admin.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(255, 159, 51);\n"
"border-style: None;\n"
"border-radius: 30px;\n"
"\n"
"}")
        self.pushButton_admin.setObjectName("pushButton_admin")
        self.pushButton_emp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_emp.setGeometry(QtCore.QRect(800, 450, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.pushButton_emp.setFont(font)
        self.pushButton_emp.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(255, 159, 51);\n"
"border-style: None;\n"
"border-radius: 30px;\n"
"\n"
"}")
        self.pushButton_emp.setObjectName("pushButton_emp")
        self.pushButton_about = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_about.setGeometry(QtCore.QRect(1190, 690, 75, 23))
        self.pushButton_about.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_about.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(255, 159, 51);\n"
"border-style: None;\n"
"border-radius: 10px;\n"
"\n"
"}")
        self.pushButton_about.setObjectName("pushButton_about")
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Pizza House"))
        LoginWindow.setWindowIcon(QtGui.QIcon("img/titleicon.jpeg"))
        self.label_2.setText(_translate("LoginWindow", "Login"))
        self.pushButton_admin.setText(_translate("LoginWindow", "Admin"))
        self.pushButton_emp.setText(_translate("LoginWindow", "Employee"))
        self.pushButton_about.setText(_translate("LoginWindow", "About us"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
